name: Clone Repository

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone openwrt-packages repository
        uses: actions/checkout@v2
        with:
          repository: kiddin9/openwrt-packages
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Copy files to target repository
        run: cp -r openwrt-packages/* oppg/
